In [1]:
import pandas as pd
import numpy as np

<h2> Aqcquiring Data</h2>

In [2]:
df = pd.read_csv('per_state_data.csv', skiprows=3)
spending_df = pd.read_csv('Final-GDP-dataset.csv')

/tmp/ipykernel_4609/64065805.py:2: DtypeWarning: Columns (33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67) have mixed types. Specify dtype option on import or set low_memory=False.
  spending_df = pd.read_csv('Final-GDP-dataset.csv')

In [3]:
df

,GeoFips,GeoName,LineCode,Description,1998,1999,2000,2001,2002,2003,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,00000,United States,NaN,Real dollar statistics,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00000,United States,1.0,Real GDP (millions of chained 2012 dollars) 1/,12045824.0,12623361.0,13138035.0,13263417.0,13488357.0,13865519.0,...,16253970.0,16553348.0,16932051.0,17390295.0,17680274.0,18076651.0,18609078.0,19036052.0,18509143.0,19609812.0
2,00000,United States,2.0,Real personal income (millions of constant (...,(NA),(NA),(NA),(NA),(NA),(NA),...,14003346.0,13999660.3,14549525.5,15207440.0,15451718.3,15876254.0,16314204.8,16897074.2,17825584.2,18412541.1
3,00000,United States,3.0,Real PCE (millions of constant (2012) dollar...,(NA),(NA),(NA),(NA),(NA),(NA),...,11047363.2,11211711.4,11515312.3,11892947.4,12187675.5,12478228.1,12837303.4,13092261.6,12700723.2,13754090.1
4,00000,United States,NaN,Current dollar statistics (millions of dollars),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1100,8/ Per capita PCE estimates are in current dol...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1101,9/ Regional price parities (RPPs) measure pric...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1102,10/ Implicit regional price deflators (IRPDs) ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103,(NA) In the latest year (NA) indicates the sta...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1104,"Last updated: December 15, 2022.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
spending_df

,Unnamed: 0,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,1998,...,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996
0,92,"""01000""",Alabama,5,SAGDP11N,1.0,...,All industry total (percent change),Percent change,3.50,...,0,0,0,0,0,0,0,0,0,0
1,93,"""01000""",Alabama,5,SAGDP11N,2.0,...,Private industries,Percentage points,3.29,...,0,0,0,0,0,0,0,0,0,0
2,94,"""01000""",Alabama,5,SAGDP11N,3.0,11,"Agriculture, forestry, fishing and hunting",Percentage points,0.18,...,0,0,0,0,0,0,0,0,0,0
3,95,"""01000""",Alabama,5,SAGDP11N,4.0,111-112,Farms,Percentage points,0.16,...,0,0,0,0,0,0,0,0,0,0
4,96,"""01000""",Alabama,5,SAGDP11N,5.0,113-115,"Forestry, fishing, and related activities",Percentage points,0.01,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86951,87675,"""98000""",Far West,8,SAGDP9S,74.0,...,Military,Millions of chained 1997 dollars,0.00,...,24159.9,24379.5,24578.8,24409.6,24590.5,23667.4,22529.0,21200.0,20008.7,19130.3
86952,87676,"""98000""",Far West,8,SAGDP9S,75.0,...,State and local,Millions of chained 1997 dollars,0.00,...,103766.6,106440.4,111946.9,115192.8,116701.3,117695.0,117865.8,117991.1,121619.9,122546.7
86953,87677,"""98000""",Far West,8,SAGDP9S,76.0,"36, 38",Electronic equipment and instruments 5/,Millions of chained 1997 dollars,0.00,...,20337.5,23995.6,24223.3,24256.5,25540.5,24652.6,25224.3,27109.3,36627.2,48358.9
86954,87678,"""98000""",Far West,8,SAGDP9S,77.0,"60, 61",Depository and nondepository institutions 6/,Millions of chained 1997 dollars,0.00,...,42820.4,43244.3,43763.3,48479.0,49381.1,40443.3,41888.3,40459.8,38577.9,36451.6
86955,87679,"""98000""",Far West,8,SAGDP9S,78.0,"73, 84, 87, 89",Business services and other services 7/,Millions of chained 1997 dollars,0.00,...,70507.8,79131.4,86488.2,96247.3,94316.8,95430.6,99108.7,105866.1,112798.4,123643.2

<b>Data Cleaning Phase</b>

In [5]:
"""Identifying unique descriptions in order to find only the income data"""
print(df['Description'].unique())

#collecting the relevant descriptions we want
categories = df['Description'].unique()
relevant_categories = [cat for cat in categories if (cat == '  Per capita personal income 6/') | 
                       (cat == '  Disposable personal income') | (cat == '  Personal income')
                       | (cat == '  Per capita disposable personal income 7/')] 
print(relevant_categories)

['Real dollar statistics'
 '  Real GDP (millions of chained 2012 dollars) 1/'
 '  Real personal income (millions of constant (2012) dollars) 2/'
 '  Real PCE (millions of constant (2012) dollars) 3/'
 'Current dollar statistics (millions of dollars)'
 '  Gross domestic product (GDP)' '  Personal income'
 '  Disposable personal income' '  Personal consumption expenditures'
 'Real per capita dollar statistics (constant 2012 dollars)'
 '  Real per capita personal income 4/' '  Real per capita PCE 5/'
 'Per capita current dollar statistics' '  Per capita personal income 6/'
 '  Per capita disposable personal income 7/'
 '  Per capita personal consumption expenditures (PCE) 8/' 'Price indexes'
 '  Regional price parities (RPPs) 9/'
 '  Implicit regional price deflator 10/' 'Employment'
 '  Total employment (number of jobs)' nan]
['  Personal income', '  Disposable personal income', '  Per capita personal income 6/', '  Per capita disposable personal income 7/']

In [6]:
"""Filtering out the irrelevant rows to get only rows with data on per capita income per state"""
per_capita_income_df = df[df['Description'] == relevant_categories[-2]]

In [7]:
per_capita_income_df

,GeoFips,GeoName,LineCode,Description,1998,1999,2000,2001,2002,2003,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
13,00000,United States,10.0,Per capita personal income 6/,27557,28693,30672,31617,31839,32717,...,44548,44798,46887,48725,49613,51550,53786,56250,59765,64143
34,01000,Alabama,10.0,Per capita personal income 6/,22668,23333,24306,25057,25648,26673,...,35824,36014,37055,38531,39014,40223,41539,43288,46179,49769
55,02000,Alaska,10.0,Per capita personal income 6/,29255,29951,32044,33626,34756,35996,...,53708,52812,55867,57575,56278,57189,59618,61316,62756,65813
76,04000,Arizona,10.0,Per capita personal income 6/,24173,24960,26388,27008,27353,28393,...,36545,37139,38756,40334,41473,43497,45466,48124,52327,55487
97,05000,Arkansas,10.0,Per capita personal income 6/,21208,21871,22781,23873,24306,25595,...,36582,36677,38749,39968,40873,41890,43384,44324,47154,50625
118,06000,California,10.0,Per capita personal income 6/,29092,30773,33410,34046,34131,35272,...,48121,48502,51266,54546,56560,58804,61508,64919,70647,76614
139,08000,Colorado,10.0,Per capita personal income 6/,29901,31305,34029,34897,34438,34856,...,45630,47404,50797,52339,52390,55251,58453,62124,65358,70706
160,09000,Connecticut,10.0,Per capita personal income 6/,37827,39700,43070,45153,44697,44997,...,64121,62647,65498,67321,68680,70011,72926,75533,78463,83294
181,10000,Delaware,10.0,Per capita personal income 6/,29472,31181,33884,36922,37658,38065,...,44070,44404,46015,47868,48734,50417,52716,54217,56324,59931
202,11000,District of Columbia,10.0,Per capita personal income 6/,38122,39798,43524,44871,45147,46011,...,68148,67774,71469,75623,78186,79984,82708,84671,89735,96477
223,12000,Florida,10.0,Per capita personal income 6/,26883,27689,29466,30418,30810,31785,...,41540,41162,43516,45659,46454,49055,51520,54560,57292,62270
244,13000,Georgia,10.0,Per capita personal income 6/,26152,27254,28851,29762,30133,30896,...,37495,37794,39969,41941,43033,44993,46855,49083,51987,55786
265,15000,Hawaii,10.0,Per capita personal income 6/,26756,27768,29319,30229,31257,32467,...,43812,43931,46044,47777,49122,51114,52164,54700,57241,60947
286,16000,Idaho,10.0,Per capita personal income 6/,22783,23688,25183,25799,26233,26728,...,35110,36095,37680,39386,40098,41457,43217,45924,49491,52369
307,17000,Illinois,10.0,Per capita personal income 6/,29930,31068,33212,34299,34594,35212,...,46029,47047,49238,51443,52036,53611,56536,58438,62139,67244
328,18000,Indiana,10.0,Per capita personal income 6/,25790,26600,28153,28639,28918,29521,...,39433,39766,41188,42667,43645,45015,46945,48749,52219,56497
349,19000,Iowa,10.0,Per capita personal income 6/,25207,25740,27390,28162,28772,29383,...,42873,43439,44699,46104,46291,47246,49163,50367,53312,57163
370,20000,Kansas,10.0,Per capita personal income 6/,26221,26927,28253,29112,29248,30074,...,45294,46174,47013,47332,47326,48651,50663,52876,55974,58924
391,21000,Kentucky,10.0,Per capita personal income 6/,22445,23224,24868,25596,26057,26687,...,35875,36058,37645,39232,39750,40751,41974,43875,47525,51266
412,22000,Louisiana,10.0,Per capita personal income 6/,22312,22746,23997,25663,26289,27022,...,41003,41376,43085,43113,42725,44056,46057,47668,50809,54217
433,23000,Maine,10.0,Per capita personal income 6/,24805,25779,27491,28824,29572,30805,...,40411,40329,41797,43672,44740,46378,48141,50728,54912,58484
454,24000,Maryland,10.0,Per capita personal income 6/,31483,33036,35591,37076,38035,39394,...,52787,52249,53659,55825,57632,59155,60577,62313,65685,69817
475,25000,Massachusetts,10.0,Per capita personal income 6/,32914,34967,38594,39872,39540,40267,...,56669,56628,58924,62376,64295,66679,69693,73213,78388,83653
496,26000,Michigan,10.0,Per capita personal income 6/,27430,28629,30344,30749,30602,31279,...,39266,39566,41207,43425,44527,45716,47457,49142,53388,56494
517,27000,Minnesota,10.0,Per capita personal income 6/,29162,30303,32448,33490,33955,35293,...,47726,47838,49967,51985,52596,54266,56539,58543,62240,66280
538,28000,Mississippi,10.0,Per capita personal income 6/,20174,20709,21681,22845,23219,24064,...,33657,34259,34896,35533,36021,36902,37900,39445,42716,45881
559,29000,Missouri,10.0,Per capita personal income 6/,25540,26342,27941,28690,29168,30085,...,40317,40569,41963,43322,44410,45239,47085,49001,52108,55325
580,30000,Montana,10.0,Per capita personal income 6/,21461,21794,23081,23996,24554,26125,...,40701,40674,42494,43941,44063,46036,47612,50289,54106,56949
601,31000,Nebraska,10.0,Per capita personal income 6/,26421,27545,29039,30275,30599,32348,...,46670,46653,48957,50556,49360,50144,51916,54182,57421,61205
622,32000,Nevada,10.0,Per capita personal income 6/,29314,30405,31986,32461,32130,33121,...,39909,39664,41773,44493,45450,47485,49678,52602,55406,60213
643,33000,New Hampshire,10.0,Per capita personal income 6/,30319,31852,35335,36747,36974,37371,...,51123,50865,52643,54684,56321,58362,60831,64747,68542,73200
664,34000,New Jersey,10.0,Per capita personal income 6/,34663,35965,39216,40245,40474,41198,...,54574,54813,57065,59175,60533,62465,64914,68438,71505,77016
685,35000,New Mexico,10.0,Per capita personal income 6/,21380,21587,23102,24601,25255,26097,...,35749,35088,37219,38103,38775,39458,41218,43530,46760,50311
706,36000,New York,10.0,Per capita personal income 6/,32040,33740,36090,37283,37088,37576,...,53102,53395,55290,57481,59280,62913,64849,67366,71577,76837
727,37000,North Carolina,10.0,Per capita personal income 6/,25440,26239,27510,27838,27852,28715,...,39103,38394,40293,42076,42936,44591,46352,48741,51900,56173
748,38000,North Dakota,10.0,Per capita personal income 6/,23285,23705,25892,26541,27218,29678,...,56443,54900,57523,53991,52005,52521,55396,57110,60864,64524
769,39000,Ohio,10.0,Per capita personal income 6/,26442,27200,28598,29323,29693,30509,...,40759,41259,42829,44442,45212,46646,48327,50035,53545,56879
790,40000,Oklahoma,10.0,Per capita personal income 6/,22006,22412,24178,25608,26023,27198,...,42232,44017,46614,44894,42521,44423,46415,48646,50518,53870
811,41000,Oregon,10.0,Per capita personal income 6/,26023,26617,28386,28829,28749,29526,...,39371,39788,42134,44694,45999,47974,50567,52718,57005,61596
832,42000,Pennsylvania,10.0,Per capita personal income 6/,27336,28489,30443,31634,32133,33170,...,45855,46213,48063,49927,51181,52421,55030,56952,60685,64279
853,44000,Rhode Island,10.0,Per capita personal income 6/,27552,28496,30417,31815,32807,34301,...,45601,45447,47199,48682,49184,50982,52659,55830,59941,64376
874,45000,South Carolina,10.0,Per capita personal income 6/,22946,23764,25133,25737,26182,26832,...,35989,36204,38152,40053,41178,42758,44155,46681,49105,52467
895,46000,South Dakota,10.0,Per capita personal income 6/,24277,25306,26825,27645,27572,29972,...,45442,45608,47488,49186,49192,50104,52166,55294,60446,64462
916,47000,Tennessee,10.0,Per capita personal income 6/,25116,25807,27066,27541,28113,29098,...,39373,39454,40753,42535,43499,44879,46870,49343,52351,56560
937,48000,Texas,10.0,Per capita personal income 6/,25556,26530,28383,29644,29524,30224,...,44241,44816,47370,47465,46586,49231,52005,54076,55601,59865
958,49000,Utah,10.0,Per capita personal income 6/,22266,23081,24260,24925,25190,25792,...,36005,36511,38168,40459,41750,43241,45665,48580,52225,56019
979,50000,Vermont,10.0,Per capita personal income 6/,25693,26963,29014,30716,31217,32338,...,45277,45770,47641,48876,49621,50771,52409,55442,59296,61882
1000,51000,Virginia,10.0,Per capita personal income 6/,28992,30637,32715,34001,34498,36188,...,49309,48573,50318,52238,53268,54879,56619,59073,62189,66305
1021,53000,Washington,10.0,Per capita personal income 6/,29513,30958,32723,33084,33212,34253,...,47320,47857,50890,53083,54918,57265,60221,64189,68350,73775
1042,54000,West Virginia,10.0,Per capita personal income 6/,20447,21037,22317,23754,24517,24823,...,35453,35318,36570,37468,37380,39140,41279,42951,45240,48488
1063,55000,Wisconsin,10.0,Per capita personal income 6/,27031,27933,29556,30841,31425,32148,...,42944,43050,44709,46548,47205,48758,50908,52893,55941,59626
1084,56000,Wyoming,10.0,Per capita personal income 6/,25755,27518,29607,31347,31854,33686,...,54213,53776,57749,57846,54827,57184,60472,64117,65782,69666

<b>Fixing the Description tags with string manipulation</b>

In [8]:
import re

In [9]:
#regex to capture only alphanumerical strings 
pattern = re.compile(r'[a-z]+', flags=re.IGNORECASE)

#capture alphanumerical strings in each description tag
relevant_categories = list(map(lambda x: pattern.findall(x), relevant_categories))

In [10]:
print(list(relevant_categories))

[['Personal', 'income'], ['Disposable', 'personal', 'income'], ['Per', 'capita', 'personal', 'income'], ['Per', 'capita', 'disposable', 'personal', 'income']]

In [11]:
#rebuild all the decription tags normalized
relevant_categories = list(map(lambda x: " ".join(x), relevant_categories))
relevant_categories

['Personal income',
 'Disposable personal income',
 'Per capita personal income',
 'Per capita disposable personal income']

In [12]:
#Get the description tag we want to focus on in our data frame
per_capita_income_tag = relevant_categories[2]
print(per_capita_income_tag)

Per capita personal income

In [13]:
#re-assign the description tags to all the description in the original data frame
per_capita_income_df.loc[:,'Description'] = [per_capita_income_tag] * 52

/tmp/ipykernel_4609/2050795435.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  per_capita_income_df.loc[:,'Description'] = [per_capita_income_tag] * 52

<b>Map state names to state code and add them as a column</b>

In [14]:
per_capita_income_df = per_capita_income_df.replace({'GeoName' : {
        'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR', 'California': 'CA',
        'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE', 'Florida': 'FL', 'Georgia': 'GA',
        'Hawaii': 'HI', 'Idaho': 'ID', 'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA', 'Kansas': 'KS',
        'Kentucky': 'KY', 'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD', 'Massachusetts': 'MA',
        'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS', 'Missouri': 'MO', 'Montana': 'MT',
        'Nebraska': 'NE', 'Nevada': 'NV', 'New Hampshire': 'NH', 'New Jersey': 'NJ', 'New Mexico': 'NM',
        'New York': 'NY', 'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH', 'Oklahoma': 'OK',
        'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC', 'South Dakota': 'SD',
        'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT', 'Vermont': 'VT', 'Virginia': 'VA', 'Washington': 'WA',
        'West Virginia': 'WV', 'Wisconsin': 'WI', 'Wyoming': 'WY', 'District of Columbia': 'DC' 
        }})

In [15]:
#drop non_relevant columns
per_capita_income_df = per_capita_income_df.drop(['GeoFips', 'LineCode', 'Description'], axis=1)

In [16]:
per_capita_income_df

,GeoName,1998,1999,2000,2001,2002,2003,2004,2005,2006,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
13,United States,27557,28693,30672,31617,31839,32717,34280,35868,38120,...,44548,44798,46887,48725,49613,51550,53786,56250,59765,64143
34,AL,22668,23333,24306,25057,25648,26673,28434,29949,31474,...,35824,36014,37055,38531,39014,40223,41539,43288,46179,49769
55,AK,29255,29951,32044,33626,34756,35996,37016,39075,41157,...,53708,52812,55867,57575,56278,57189,59618,61316,62756,65813
76,AZ,24173,24960,26388,27008,27353,28393,30221,32327,34703,...,36545,37139,38756,40334,41473,43497,45466,48124,52327,55487
97,AR,21208,21871,22781,23873,24306,25595,27059,28227,29617,...,36582,36677,38749,39968,40873,41890,43384,44324,47154,50625
118,CA,29092,30773,33410,34046,34131,35272,37070,38932,41746,...,48121,48502,51266,54546,56560,58804,61508,64919,70647,76614
139,CO,29901,31305,34029,34897,34438,34856,35819,37797,40137,...,45630,47404,50797,52339,52390,55251,58453,62124,65358,70706
160,CT,37827,39700,43070,45153,44697,44997,47238,49738,53696,...,64121,62647,65498,67321,68680,70011,72926,75533,78463,83294
181,DE,29472,31181,33884,36922,37658,38065,38974,39370,41053,...,44070,44404,46015,47868,48734,50417,52716,54217,56324,59931
202,DC,38122,39798,43524,44871,45147,46011,50088,52947,55805,...,68148,67774,71469,75623,78186,79984,82708,84671,89735,96477
223,FL,26883,27689,29466,30418,30810,31785,33778,35999,38386,...,41540,41162,43516,45659,46454,49055,51520,54560,57292,62270
244,GA,26152,27254,28851,29762,30133,30896,32034,33445,34791,...,37495,37794,39969,41941,43033,44993,46855,49083,51987,55786
265,HI,26756,27768,29319,30229,31257,32467,34277,36375,38480,...,43812,43931,46044,47777,49122,51114,52164,54700,57241,60947
286,ID,22783,23688,25183,25799,26233,26728,28317,29392,31476,...,35110,36095,37680,39386,40098,41457,43217,45924,49491,52369
307,IL,29930,31068,33212,34299,34594,35212,36519,37975,40365,...,46029,47047,49238,51443,52036,53611,56536,58438,62139,67244
328,IN,25790,26600,28153,28639,28918,29521,30791,31566,33123,...,39433,39766,41188,42667,43645,45015,46945,48749,52219,56497
349,IA,25207,25740,27390,28162,28772,29383,31704,32621,34448,...,42873,43439,44699,46104,46291,47246,49163,50367,53312,57163
370,KS,26221,26927,28253,29112,29248,30074,30843,32545,35690,...,45294,46174,47013,47332,47326,48651,50663,52876,55974,58924
391,KY,22445,23224,24868,25596,26057,26687,28087,29241,30660,...,35875,36058,37645,39232,39750,40751,41974,43875,47525,51266
412,LA,22312,22746,23997,25663,26289,27022,28065,30139,33850,...,41003,41376,43085,43113,42725,44056,46057,47668,50809,54217
433,ME,24805,25779,27491,28824,29572,30805,32211,32925,34451,...,40411,40329,41797,43672,44740,46378,48141,50728,54912,58484
454,MD,31483,33036,35591,37076,38035,39394,41641,43515,45576,...,52787,52249,53659,55825,57632,59155,60577,62313,65685,69817
475,MA,32914,34967,38594,39872,39540,40267,42407,44371,47750,...,56669,56628,58924,62376,64295,66679,69693,73213,78388,83653
496,MI,27430,28629,30344,30749,30602,31279,32168,32946,33812,...,39266,39566,41207,43425,44527,45716,47457,49142,53388,56494
517,MN,29162,30303,32448,33490,33955,35293,37211,38065,39667,...,47726,47838,49967,51985,52596,54266,56539,58543,62240,66280
538,MS,20174,20709,21681,22845,23219,24064,25306,26835,27981,...,33657,34259,34896,35533,36021,36902,37900,39445,42716,45881
559,MO,25540,26342,27941,28690,29168,30085,31510,32467,34119,...,40317,40569,41963,43322,44410,45239,47085,49001,52108,55325
580,MT,21461,21794,23081,23996,24554,26125,28131,30074,32193,...,40701,40674,42494,43941,44063,46036,47612,50289,54106,56949
601,NE,26421,27545,29039,30275,30599,32348,33627,34666,36019,...,46670,46653,48957,50556,49360,50144,51916,54182,57421,61205
622,NV,29314,30405,31986,32461,32130,33121,35232,38109,39767,...,39909,39664,41773,44493,45450,47485,49678,52602,55406,60213
643,NH,30319,31852,35335,36747,36974,37371,39434,40619,43153,...,51123,50865,52643,54684,56321,58362,60831,64747,68542,73200
664,NJ,34663,35965,39216,40245,40474,41198,42876,44467,47695,...,54574,54813,57065,59175,60533,62465,64914,68438,71505,77016
685,NM,21380,21587,23102,24601,25255,26097,27399,28858,30597,...,35749,35088,37219,38103,38775,39458,41218,43530,46760,50311
706,NY,32040,33740,36090,37283,37088,37576,39329,40884,44128,...,53102,53395,55290,57481,59280,62913,64849,67366,71577,76837
727,NC,25440,26239,27510,27838,27852,28715,30635,32345,34385,...,39103,38394,40293,42076,42936,44591,46352,48741,51900,56173
748,ND,23285,23705,25892,26541,27218,29678,30107,31967,33357,...,56443,54900,57523,53991,52005,52521,55396,57110,60864,64524
769,OH,26442,27200,28598,29323,29693,30509,31660,32607,34214,...,40759,41259,42829,44442,45212,46646,48327,50035,53545,56879
790,OK,22006,22412,24178,25608,26023,27198,29264,31856,34854,...,42232,44017,46614,44894,42521,44423,46415,48646,50518,53870
811,OR,26023,26617,28386,28829,28749,29526,30996,32296,34716,...,39371,39788,42134,44694,45999,47974,50567,52718,57005,61596
832,PA,27336,28489,30443,31634,32133,33170,34984,36410,38109,...,45855,46213,48063,49927,51181,52421,55030,56952,60685,64279
853,RI,27552,28496,30417,31815,32807,34301,35927,36984,39028,...,45601,45447,47199,48682,49184,50982,52659,55830,59941,64376
874,SC,22946,23764,25133,25737,26182,26832,27986,29285,30984,...,35989,36204,38152,40053,41178,42758,44155,46681,49105,52467
895,SD,24277,25306,26825,27645,27572,29972,32025,33788,35299,...,45442,45608,47488,49186,49192,50104,52166,55294,60446,64462
916,TN,25116,25807,27066,27541,28113,29098,30472,31548,33065,...,39373,39454,40753,42535,43499,44879,46870,49343,52351,56560
937,TX,25556,26530,28383,29644,29524,30224,31195,33276,35630,...,44241,44816,47370,47465,46586,49231,52005,54076,55601,59865
958,UT,22266,23081,24260,24925,25190,25792,27018,28927,31327,...,36005,36511,38168,40459,41750,43241,45665,48580,52225,56019
979,VT,25693,26963,29014,30716,31217,32338,34087,34878,37008,...,45277,45770,47641,48876,49621,50771,52409,55442,59296,61882
1000,VA,28992,30637,32715,34001,34498,36188,38139,40167,42385,...,49309,48573,50318,52238,53268,54879,56619,59073,62189,66305
1021,WA,29513,30958,32723,33084,33212,34253,36378,37384,40027,...,47320,47857,50890,53083,54918,57265,60221,64189,68350,73775
1042,WV,20447,21037,22317,23754,24517,24823,25687,26981,28704,...,35453,35318,36570,37468,37380,39140,41279,42951,45240,48488
1063,WI,27031,27933,29556,30841,31425,32148,33424,34447,36338,...,42944,43050,44709,46548,47205,48758,50908,52893,55941,59626
1084,WY,25755,27518,29607,31347,31854,33686,36065,39385,44492,...,54213,53776,57749,57846,54827,57184,60472,64117,65782,69666

In [17]:
#remove first row
per_capita_income_df = per_capita_income_df[1:]

In [18]:


regions = spending_df[['GeoName', 'Region']]


regions = regions.replace({'GeoName' : {
        'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR', 'California': 'CA',
        'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE', 'Florida': 'FL', 'Georgia': 'GA',
        'Hawaii': 'HI', 'Idaho': 'ID', 'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA', 'Kansas': 'KS',
        'Kentucky': 'KY', 'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD', 'Massachusetts': 'MA',
        'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS', 'Missouri': 'MO', 'Montana': 'MT',
        'Nebraska': 'NE', 'Nevada': 'NV', 'New Hampshire': 'NH', 'New Jersey': 'NJ', 'New Mexico': 'NM',
        'New York': 'NY', 'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH', 'Oklahoma': 'OK',
        'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC', 'South Dakota': 'SD',
        'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT', 'Vermont': 'VT', 'Virginia': 'VA', 'Washington': 'WA',
        'West Virginia': 'WV', 'Wisconsin': 'WI', 'Wyoming': 'WY', 'District of Columbia': 'DC' 
        }})

In [19]:
#mapping state code to region code
per_capita_income_df = pd.merge(per_capita_income_df, regions, left_on='GeoName', right_on='GeoName')

KeyError: "['GeoName'] not found in axis"

In [20]:
per_capita_income_df

,GeoName,1998,1999,2000,2001,2002,2003,2004,2005,2006,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Region
0,AL,22668,23333,24306,25057,25648,26673,28434,29949,31474,...,36014,37055,38531,39014,40223,41539,43288,46179,49769,5
1,AL,22668,23333,24306,25057,25648,26673,28434,29949,31474,...,36014,37055,38531,39014,40223,41539,43288,46179,49769,5
2,AL,22668,23333,24306,25057,25648,26673,28434,29949,31474,...,36014,37055,38531,39014,40223,41539,43288,46179,49769,5
3,AL,22668,23333,24306,25057,25648,26673,28434,29949,31474,...,36014,37055,38531,39014,40223,41539,43288,46179,49769,5
4,AL,22668,23333,24306,25057,25648,26673,28434,29949,31474,...,36014,37055,38531,39014,40223,41539,43288,46179,49769,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74455,WY,25755,27518,29607,31347,31854,33686,36065,39385,44492,...,53776,57749,57846,54827,57184,60472,64117,65782,69666,7
74456,WY,25755,27518,29607,31347,31854,33686,36065,39385,44492,...,53776,57749,57846,54827,57184,60472,64117,65782,69666,7
74457,WY,25755,27518,29607,31347,31854,33686,36065,39385,44492,...,53776,57749,57846,54827,57184,60472,64117,65782,69666,7
74458,WY,25755,27518,29607,31347,31854,33686,36065,39385,44492,...,53776,57749,57846,54827,57184,60472,64117,65782,69666,7
74459,WY,25755,27518,29607,31347,31854,33686,36065,39385,44492,...,53776,57749,57846,54827,57184,60472,64117,65782,69666,7

In [23]:

per_capita_income_df = per_capita_income_df.drop_duplicates()

In [24]:
per_capita_income_df

,GeoName,1998,1999,2000,2001,2002,2003,2004,2005,2006,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Region
0,AL,22668,23333,24306,25057,25648,26673,28434,29949,31474,...,36014,37055,38531,39014,40223,41539,43288,46179,49769,5
1460,AK,29255,29951,32044,33626,34756,35996,37016,39075,41157,...,52812,55867,57575,56278,57189,59618,61316,62756,65813,8
2920,AZ,24173,24960,26388,27008,27353,28393,30221,32327,34703,...,37139,38756,40334,41473,43497,45466,48124,52327,55487,6
4380,AR,21208,21871,22781,23873,24306,25595,27059,28227,29617,...,36677,38749,39968,40873,41890,43384,44324,47154,50625,5
5840,CA,29092,30773,33410,34046,34131,35272,37070,38932,41746,...,48502,51266,54546,56560,58804,61508,64919,70647,76614,8
7300,CO,29901,31305,34029,34897,34438,34856,35819,37797,40137,...,47404,50797,52339,52390,55251,58453,62124,65358,70706,7
8760,CT,37827,39700,43070,45153,44697,44997,47238,49738,53696,...,62647,65498,67321,68680,70011,72926,75533,78463,83294,1
10220,DE,29472,31181,33884,36922,37658,38065,38974,39370,41053,...,44404,46015,47868,48734,50417,52716,54217,56324,59931,2
11680,DC,38122,39798,43524,44871,45147,46011,50088,52947,55805,...,67774,71469,75623,78186,79984,82708,84671,89735,96477,2
13140,FL,26883,27689,29466,30418,30810,31785,33778,35999,38386,...,41162,43516,45659,46454,49055,51520,54560,57292,62270,5
14600,GA,26152,27254,28851,29762,30133,30896,32034,33445,34791,...,37794,39969,41941,43033,44993,46855,49083,51987,55786,5
16060,HI,26756,27768,29319,30229,31257,32467,34277,36375,38480,...,43931,46044,47777,49122,51114,52164,54700,57241,60947,8
17520,ID,22783,23688,25183,25799,26233,26728,28317,29392,31476,...,36095,37680,39386,40098,41457,43217,45924,49491,52369,7
18980,IL,29930,31068,33212,34299,34594,35212,36519,37975,40365,...,47047,49238,51443,52036,53611,56536,58438,62139,67244,3
20440,IN,25790,26600,28153,28639,28918,29521,30791,31566,33123,...,39766,41188,42667,43645,45015,46945,48749,52219,56497,3
21900,IA,25207,25740,27390,28162,28772,29383,31704,32621,34448,...,43439,44699,46104,46291,47246,49163,50367,53312,57163,4
23360,KS,26221,26927,28253,29112,29248,30074,30843,32545,35690,...,46174,47013,47332,47326,48651,50663,52876,55974,58924,4
24820,KY,22445,23224,24868,25596,26057,26687,28087,29241,30660,...,36058,37645,39232,39750,40751,41974,43875,47525,51266,5
26280,LA,22312,22746,23997,25663,26289,27022,28065,30139,33850,...,41376,43085,43113,42725,44056,46057,47668,50809,54217,5
27740,ME,24805,25779,27491,28824,29572,30805,32211,32925,34451,...,40329,41797,43672,44740,46378,48141,50728,54912,58484,1
29200,MD,31483,33036,35591,37076,38035,39394,41641,43515,45576,...,52249,53659,55825,57632,59155,60577,62313,65685,69817,2
30660,MA,32914,34967,38594,39872,39540,40267,42407,44371,47750,...,56628,58924,62376,64295,66679,69693,73213,78388,83653,1
32120,MI,27430,28629,30344,30749,30602,31279,32168,32946,33812,...,39566,41207,43425,44527,45716,47457,49142,53388,56494,3
33580,MN,29162,30303,32448,33490,33955,35293,37211,38065,39667,...,47838,49967,51985,52596,54266,56539,58543,62240,66280,4
35040,MS,20174,20709,21681,22845,23219,24064,25306,26835,27981,...,34259,34896,35533,36021,36902,37900,39445,42716,45881,5
36500,MO,25540,26342,27941,28690,29168,30085,31510,32467,34119,...,40569,41963,43322,44410,45239,47085,49001,52108,55325,4
37960,MT,21461,21794,23081,23996,24554,26125,28131,30074,32193,...,40674,42494,43941,44063,46036,47612,50289,54106,56949,7
39420,NE,26421,27545,29039,30275,30599,32348,33627,34666,36019,...,46653,48957,50556,49360,50144,51916,54182,57421,61205,4
40880,NV,29314,30405,31986,32461,32130,33121,35232,38109,39767,...,39664,41773,44493,45450,47485,49678,52602,55406,60213,8
42340,NH,30319,31852,35335,36747,36974,37371,39434,40619,43153,...,50865,52643,54684,56321,58362,60831,64747,68542,73200,1
43800,NJ,34663,35965,39216,40245,40474,41198,42876,44467,47695,...,54813,57065,59175,60533,62465,64914,68438,71505,77016,2
45260,NM,21380,21587,23102,24601,25255,26097,27399,28858,30597,...,35088,37219,38103,38775,39458,41218,43530,46760,50311,6
46720,NY,32040,33740,36090,37283,37088,37576,39329,40884,44128,...,53395,55290,57481,59280,62913,64849,67366,71577,76837,2
48180,NC,25440,26239,27510,27838,27852,28715,30635,32345,34385,...,38394,40293,42076,42936,44591,46352,48741,51900,56173,5
49640,ND,23285,23705,25892,26541,27218,29678,30107,31967,33357,...,54900,57523,53991,52005,52521,55396,57110,60864,64524,4
51100,OH,26442,27200,28598,29323,29693,30509,31660,32607,34214,...,41259,42829,44442,45212,46646,48327,50035,53545,56879,3
52560,OK,22006,22412,24178,25608,26023,27198,29264,31856,34854,...,44017,46614,44894,42521,44423,46415,48646,50518,53870,6
54020,OR,26023,26617,28386,28829,28749,29526,30996,32296,34716,...,39788,42134,44694,45999,47974,50567,52718,57005,61596,8
55480,PA,27336,28489,30443,31634,32133,33170,34984,36410,38109,...,46213,48063,49927,51181,52421,55030,56952,60685,64279,2
56940,RI,27552,28496,30417,31815,32807,34301,35927,36984,39028,...,45447,47199,48682,49184,50982,52659,55830,59941,64376,1
58400,SC,22946,23764,25133,25737,26182,26832,27986,29285,30984,...,36204,38152,40053,41178,42758,44155,46681,49105,52467,5
59860,SD,24277,25306,26825,27645,27572,29972,32025,33788,35299,...,45608,47488,49186,49192,50104,52166,55294,60446,64462,4
61320,TN,25116,25807,27066,27541,28113,29098,30472,31548,33065,...,39454,40753,42535,43499,44879,46870,49343,52351,56560,5
62780,TX,25556,26530,28383,29644,29524,30224,31195,33276,35630,...,44816,47370,47465,46586,49231,52005,54076,55601,59865,6
64240,UT,22266,23081,24260,24925,25190,25792,27018,28927,31327,...,36511,38168,40459,41750,43241,45665,48580,52225,56019,7
65700,VT,25693,26963,29014,30716,31217,32338,34087,34878,37008,...,45770,47641,48876,49621,50771,52409,55442,59296,61882,1
67160,VA,28992,30637,32715,34001,34498,36188,38139,40167,42385,...,48573,50318,52238,53268,54879,56619,59073,62189,66305,5
68620,WA,29513,30958,32723,33084,33212,34253,36378,37384,40027,...,47857,50890,53083,54918,57265,60221,64189,68350,73775,8
70080,WV,20447,21037,22317,23754,24517,24823,25687,26981,28704,...,35318,36570,37468,37380,39140,41279,42951,45240,48488,5
71540,WI,27031,27933,29556,30841,31425,32148,33424,34447,36338,...,43050,44709,46548,47205,48758,50908,52893,55941,59626,3
73000,WY,25755,27518,29607,31347,31854,33686,36065,39385,44492,...,53776,57749,57846,54827,57184,60472,64117,65782,69666,7

In [31]:
cols = ['2005', '2014', '2015', '2016', '2017', '2018', '2019', '2020']
per_capita_income_df = per_capita_income_df.groupby('Region')[cols].mean()

In [32]:
per_capita_income_df

,2005,2014,2015,2016,2017,2018,2019,2020
Region,,,,,,,,
1,8.289722e+28,1.091640e+29,1.122024e+29,1.144674e+29,1.166858e+29,1.215441e+29,1.258892e+29,1.307726e+29
2,6.561755e+28,7.669286e+28,7.978126e+28,8.122464e+28,8.402967e+28,8.786138e+28,9.036308e+28,9.387483e+28
3,7.595063e+23,9.847682e+23,1.028869e+24,1.040729e+24,1.072229e+24,1.130729e+24,1.168770e+24,1.242790e+24
4,4.660189e+33,6.385639e+33,6.586353e+33,6.613068e+33,6.749498e+33,7.023358e+33,7.195361e+33,7.616080e+33
5,2.495774e+58,3.087949e+58,3.210950e+58,3.251201e+58,3.351952e+58,3.461619e+58,3.607370e+58,3.848289e+58
6,8.081822e+18,9.689093e+18,1.008360e+19,1.036835e+19,1.087435e+19,1.136660e+19,1.203111e+19,1.308187e+19
7,7.559459e+23,1.015948e+24,1.046788e+24,1.047808e+24,1.105028e+24,1.169069e+24,1.242489e+24,1.307170e+24
8,6.512565e+28,9.311252e+28,9.595924e+28,9.379761e+28,9.531598e+28,9.936436e+28,1.021944e+29,1.045945e+29

In [33]:
#per_capita_income_df.to_csv('Income-Final.csv')